url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: "michalwa"

include: ["_pages"]
exclude:
  - package.json
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js

permalink: pretty
